language: php

php:
  - 5.3
  - 5.4
  - 5.5

env:
  - DB=mysql
  - DB=sqlite

before_script:
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'create database IF NOT EXISTS yiitest;'; fi"

script: phpunit